# Find more information on toml format here:  https://github.com/toml-lang/toml
modLoader="javafml" 
loaderVersion="[43,)" 
license="GPLv3"
issueTrackerURL="https://github.com/Klairm/Roll-It-Craft/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="projectm" #mandatory
version="0.0.1" 
displayName="Roll it Craft" 
displayURL="https://github.com/Klairm/Roll-It-Craft" 
logoFile="que.png" 
authors="Klairm" 
description='''
A mod to create and consume drugs
'''
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
